---
- name: create service for deployment
  hosts: kubemaster
  become: true

  tasks:
  - name: Copying kube file to kubemaster
    copy: src=user-movies-rating.yml dest=/home/vagrant/user-movies-rating.yml
  
  - name: create a service
    become: true
    become_user: kube
    command: kubectl apply -f /home/vagrant/user-movies-rating.yml

