apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: usermoviesrating     # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: usermoviesrating
spec:
  replicas: 1                   # tells deployment to run 1 pod matching the template
  selector:
    matchLabels:                # The deployment applies to any pods mayching the specified labels
      app: usermoviesrating

  template:                     # Template for creating the pods in this deployment
    metadata:
      labels:                   # Labels that will be applied to each Pod in this deployment
        app: usermoviesrating

    spec:                       # Spec for the containers that will be run in the Pods
      containers:
      - name: usermoviesrating
        image: amandavkar/user-movies-rating
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        env:   # Setting Enviornmental Variables
        - name: DB_HOST   # Setting Database host address from configMap
          valueFrom: 
            configMapKeyRef:
              name: db-conf  # name of configMap
              key: host
        - name: DB_NAME  # Setting Database name from configMap
          valueFrom:
            configMapKeyRef:
              name: db-conf 
              key: name
        - name: DB_USERNAME  # Setting Database username from Secret
          valueFrom:
            secretKeyRef:
              name: db-credentials # Secret Name
              key: username
        - name: DB_PASSWORD # Setting Database password from Secret
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password     
---
apiVersion: v1
kind: Service

metadata:
  name: usermoviesrating
  labels:
    app: usermoviesrating

spec:
  selector:
    app: usermoviesrating
  type: NodePort # Can use type as LoadBalancer if more than 1 replica
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
